# Config for chest_xray Images

name: "CNN-chest_xray"

# Pre-trained model
model-name: "inceptionv3"
input-height: 299
input-width: 299

# Model training parameters
num-classes: 2
batch-size: 8
epochs: 20
lr: 0.001

# Directories
train-dir: "data/chest_xray/train"
test-dir: "data/chest_xray/test"
val-dir: "data/chest_xray/val"

# Image augmentation
input-mean: [0.485, 0.456, 0.406]
input-std: [0.229, 0.224, 0.225]

# Bottlenecks (features)
features:
  root: "data/chest_xray/features"
  train: "data/chest_xray/features/train"
  test: "data/chest_xray/features/test"
  val: "data/chest_xray/features/val"
