# Template config for different models

name: ""

# Pre-trained model
model-name: ""
checkpoint: ""
fine-tune: false
embedding-size: 768

# Training parameters
num-classes: 2
batch-size:
  feature-extraction: 64
  fine-tuning: 8
  clf: 1024
epochs: 20
lr: 0.001

# dataset (kaggle)
dataset: ""

# Directories
train-dir: "data/"
test-dir: "data/"
val-dir: "data/"

# Image augmentation
transforms:
  - - RandomHorizontalFlip
    - {}
  - - RandomVerticalFlip
    - {}
  - - RandomRotation
    - degrees: 30
  - - RandomResizedCrop
    - size: [299, 299]
  - - ColorJitter
    - brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.2
  - - RandomGrayscale
    - p: 0.2
  - - Resize
    - size: [299, 299]
  - - ToTensor
    - {}
  - - Normalize
    - mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Bottlenecks (features)
features: "data/features"
