# Config for IncpetionV3 (Feature Extractor) on Brain MRI Images

name: "InceptionV3-FE-MRI"

# Pre-trained model
model-name: "inceptionv3"
fine-tune: false
embedding-dim: 2048

# Training parameters
num-classes: 4
batch-size:
  feature-extraction: 64
  clf: 1024
epochs: 50
lr: 0.001

# dataset (kaggle)
dataset: "mri"

# Directories
train-dir: "data/mri/train"
test-dir: "data/mri/test"
val-dir: "data/mri/val"

# Image augmentation
transforms:
  - - ToTensor
    - {}
  - - Resize
    - size: [299, 299]
  - - Normalize
    - mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Bottlenecks (features)
features: "data/mri/InceptionV3-features"
