# Config for IncpetionV3 (Feature Extractor) on Chest X-Ray Images

name: "InceptionV3-FE-XRay"

# Pre-trained model
model-name: "inceptionv3"
fine-tune: false

# Training parameters
num-classes: 2
batch-size:
  feature-extraction: 64
  clf-only: 1024
epochs: 50
lr: 0.001

# dataset (kaggle)
dataset: "xray"

# Directories
train-dir: "data/chest_xray/train"
test-dir: "data/chest_xray/test"
val-dir: "data/chest_xray/val"

# Image augmentation
transforms:
  - - ToTensor
    - {}
  - - Resize
    - size: [299, 299]
  - - Normalize
    - mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Bottlenecks (features)
features: "data/chest_xray/InceptionV3-features"
