# Config for ViT-base (Feature Extractor) on OCT Images

name: "ViTb-FE-XRay"

# Pre-trained model
model-name: "ViT-base"
checkpoint: "google/vit-base-patch16-224"
fine-tune: false
embedding-dim: 768

# Training parameters
num-classes: 2
batch-size:
  feature-extraction: 64
  clf-only: 1024
epochs: 50
lr: 0.001

# Directories
train-dir: "data/chest_xray/train"
test-dir: "data/chest_xray/test"
val-dir: "data/chest_xray/val"

# Training augmentation
train-augmentation:
  - - ToTensor
    - {}
  - - Resize
    - size: [299, 299]
  - - Normalize
    - mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Testing augmentation
test-augmentation:
  - - ToTensor
    - {}
  - - Resize
    - size: [299, 299]
  - - Normalize
    - mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Bottlenecks (features)
features: "data/chest_xray/ViTb-features"
